// macOS-only Swift↔Rust bridge. Compiled in only when both
// `target_os = "macos"` AND the `swift` feature are enabled.
//
// The actual Swift sources (`PhenoShell.swift`, `PhenoShellApp.swift`)
// will live in `mobile/macos-shell/swift/` and are generated by the
// `swift-rs` build script. For now this module is a placeholder so
// the scaffold type-checks.
//
// PILLAR-TAXONOMY-v2 **L121** (macOS Native FFI — AppKit via swift-rs).
// PILLAR-TAXONOMY-v2 **L127** (FFI Build & Toolchain — swift-rs).

#![cfg(all(target_os = "macos", feature = "swift"))]

/// Swift-callable entry point invoked from `PhenoShell.swift`.
pub fn pheno_shell_boot() -> Result<(), i32> {
    // Real implementation will use:
    //   swift_rs::SwiftLinker::new().link();
    // plus an `extern "C"` Swift shim that constructs NSApplication.
    Ok(())
}

/// Forward a deploy-event payload to the Swift side.
pub fn pheno_shell_notify(event_id: &str, payload: &str) -> Result<(), i32> {
    let _ = (event_id, payload);
    Ok(())
}