//! launchd plist host — registers `pheno-compose-driver` as a per-user
//! launchd agent so it boots on login and restarts on crash.
//!
//! PILLAR-TAXONOMY-v2 **L130** (System Service Integration — launchd-plist
//! for macOS).
//!
//! On non-macOS targets the module is compiled but the install helpers
//! short-circuit to a `BridgeUnavailable` error so the host driver can
//! still query the API surface without crashing.

use std::path::{Path, PathBuf};

use super::{MacosShellError, ShellCapabilities};

pub const LAUNCHD_LABEL: &str = "ai.phenotype.pheno-compose-driver";
pub const PLIST_FILENAME: &str = "ai.phenotype.pheno-compose-driver.plist";

/// Where the plist should be installed for the current user.
/// `~/Library/LaunchAgents/` is the standard per-user agent location.
pub fn launch_agent_dir() -> Result<PathBuf, MacosShellError> {
    let home = std::env::var_os("HOME")
        .ok_or_else(|| MacosShellError::LaunchdBootstrap("$HOME not set".into()))?;
    Ok(Path::new(&home).join("Library").join("LaunchAgents"))
}

/// Render the launchd plist body for `pheno-compose-driver`. The exact
/// binary path and program-args will be filled in once the macOS build
/// pipeline lands — for now the placeholder mirrors the eventual shape.
pub fn render_plist(driver_binary: &Path) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- PhenoCompose launchd plist (PILLAR-TAXONOMY-v2 L130).
     Generated by pheno-macos-shell scaffold; review before shipping. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>

    <key>ProgramArguments</key>
    <array>
        <string>{bin}</string>
        <string>service-mode</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
        <key>Crashed</key>
        <true/>
    </dict>

    <key>ProcessType</key>
    <string>Background</string>

    <key>StandardOutPath</key>
    <string>/tmp/pheno-compose-driver.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/pheno-compose-driver.err.log</string>
</dict>
</plist>
"#,
        label = LAUNCHD_LABEL,
        bin = driver_binary.display(),
    )
}

/// Install the plist into `~/Library/LaunchAgents/`. On non-macOS this
/// returns `BridgeUnavailable` so the scaffold compiles cross-platform.
pub fn install_plist(driver_binary: &Path) -> Result<PathBuf, MacosShellError> {
    #[cfg(target_os = "macos")]
    {
        let dir = launch_agent_dir()?;
        std::fs::create_dir_all(&dir)
            .map_err(|e| MacosShellError::LaunchdBootstrap(format!("mkdir {:?}: {}", dir, e)))?;
        let dest = dir.join(PLIST_FILENAME);
        std::fs::write(&dest, render_plist(driver_binary))
            .map_err(|e| MacosShellError::LaunchdBootstrap(format!("write {:?}: {}", dest, e)))?;
        Ok(dest)
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = driver_binary;
        Err(MacosShellError::BridgeUnavailable)
    }
}

/// Capability query for the launchd surface — used by `boot_shell_extension`
/// to populate `ShellCapabilities.launchd_service`.
pub fn capabilities() -> ShellCapabilities {
    let mut caps = ShellCapabilities::default();
    caps.launchd_service = cfg!(target_os = "macos");
    caps
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn plist_contains_label_and_binary() {
        let body = render_plist(Path::new("/usr/local/bin/pheno-compose-driver"));
        assert!(body.contains(LAUNCHD_LABEL));
        assert!(body.contains("/usr/local/bin/pheno-compose-driver"));
        assert!(body.contains("<key>RunAtLoad</key>"));
    }

    #[test]
    fn install_is_unsupported_off_macos() {
        #[cfg(not(target_os = "macos"))]
        {
            let err = install_plist(Path::new("/bin/true")).unwrap_err();
            assert!(matches!(err, MacosShellError::BridgeUnavailable));
        }
    }
}