/**
 * Global Teardown for Integration Tests
 * 
 * Runs once after all integration tests complete to clean up resources,
 * generate reports, and archive test results.
 */

import { promises as fs } from "fs";
import path from "path";

export default async function globalTeardown() {
  console.log("🏁 Global Integration Test Teardown Starting...");
  
  try {
    // Generate test summary report
    await generateTestSummary();
    
    // Archive test results
    await archiveTestResults();
    
    // Clean up temporary resources
    await cleanupTemporaryResources();
    
    // Generate coverage summary
    await generateCoverageSummary();
    
    // Validate test environment state
    await validateTestEnvironment();
    
    console.log("✅ Global Integration Test Teardown Completed Successfully");
  } catch (error) {
    console.error("❌ Global Teardown Error:", error);
    // Don't throw - teardown errors shouldn't fail the test suite
  }
}

/**
 * Generate comprehensive test summary report
 */
async function generateTestSummary(): Promise<void> {
  try {
    const resultsPath = "./test-results/integration/results.json";
    const summaryPath = "./test-results/integration/summary.md";
    
    let results: any = {};
    try {
      const resultsContent = await fs.readFile(resultsPath, "utf-8");
      results = JSON.parse(resultsContent);
    } catch {
      console.log("⚠️ No test results found, creating empty summary");
    }
    
    const summary = generateMarkdownSummary(results);
    await fs.writeFile(summaryPath, summary);
    
    console.log("📊 Test summary report generated");
  } catch (error) {
    console.error("Failed to generate test summary:", error);
  }
}

/**
 * Generate markdown summary from test results
 */
function generateMarkdownSummary(results: any): string {
  const timestamp = new Date().toISOString();
  const testFiles = results.testResults || [];
  
  let totalTests = 0;
  let passedTests = 0;
  let failedTests = 0;
  let skippedTests = 0;
  
  testFiles.forEach((file: any) => {
    totalTests += file.numTotalTests || 0;
    passedTests += file.numPassingTests || 0;
    failedTests += file.numFailingTests || 0;
    skippedTests += file.numTodoTests || 0;
  });
  
  const passRate = totalTests > 0 ? ((passedTests / totalTests) * 100).toFixed(2) : "0";
  const duration = results.testDuration || 0;
  
  return `# Integration Test Summary
  
## Test Execution Report
**Generated:** ${timestamp}
**Duration:** ${(duration / 1000).toFixed(2)} seconds
**Pass Rate:** ${passRate}%

## Test Statistics
| Metric | Count |
|--------|--------|
| Total Tests | ${totalTests} |
| ✅ Passed | ${passedTests} |
| ❌ Failed | ${failedTests} |
| ⏭️ Skipped | ${skippedTests} |

## Test Files Executed
${testFiles.map((file: any) => {
  const fileName = path.basename(file.name || "Unknown");
  const status = file.status === "passed" ? "✅" : file.status === "failed" ? "❌" : "⚠️";
  const duration = ((file.endTime - file.startTime) / 1000).toFixed(2);
  return `- ${status} **${fileName}** (${duration}s)`;
}).join("\n")}

## Coverage Summary
${results.coverage ? 
  `- **Statements:** ${results.coverage.statements?.pct || 0}%
- **Branches:** ${results.coverage.branches?.pct || 0}%
- **Functions:** ${results.coverage.functions?.pct || 0}%
- **Lines:** ${results.coverage.lines?.pct || 0}%` : 
  "Coverage data not available"}

## Failed Tests
${testFiles.filter((file: any) => file.status === "failed").map((file: any) => {
  return `### ${path.basename(file.name)}
${file.failureMessage ? "```\n" + file.failureMessage + "\n```" : "No failure details available"}`;
}).join("\n\n") || "No failed tests"}

## Performance Metrics
- **Slowest Test:** ${findSlowestTest(testFiles)}
- **Memory Usage:** ${getMemoryUsage()}
- **Average Test Duration:** ${getAverageTestDuration(testFiles)}

---
*Generated by Integration Test Suite*`;
}

/**
 * Find the slowest test for performance reporting
 */
function findSlowestTest(testFiles: any[]): string {
  let slowest = { name: "N/A", duration: 0 };
  
  testFiles.forEach(file => {
    const duration = file.endTime - file.startTime;
    if (duration > slowest.duration) {
      slowest = { name: path.basename(file.name || "Unknown"), duration };
    }
  });
  
  return slowest.duration > 0 ? `${slowest.name} (${(slowest.duration / 1000).toFixed(2)}s)` : "N/A";
}

/**
 * Get memory usage information
 */
function getMemoryUsage(): string {
  const usage = process.memoryUsage();
  return `${(usage.heapUsed / 1024 / 1024).toFixed(2)} MB`;
}

/**
 * Calculate average test duration
 */
function getAverageTestDuration(testFiles: any[]): string {
  if (testFiles.length === 0) return "N/A";
  
  const totalDuration = testFiles.reduce((sum, file) => {
    return sum + (file.endTime - file.startTime);
  }, 0);
  
  const average = totalDuration / testFiles.length / 1000;
  return `${average.toFixed(2)}s`;
}

/**
 * Archive test results for historical tracking
 */
async function archiveTestResults(): Promise<void> {
  try {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const archiveDir = `./test-results/integration/archive/${timestamp}`;
    
    await fs.mkdir(archiveDir, { recursive: true });
    
    // Archive main results
    const filesToArchive = [
      "results.json",
      "report.html", 
      "junit.xml",
      "summary.md",
    ];
    
    await Promise.all(
      filesToArchive.map(async (file) => {
        const sourcePath = `./test-results/integration/${file}`;
        const destPath = `${archiveDir}/${file}`;
        
        try {
          await fs.copyFile(sourcePath, destPath);
        } catch {
          // File might not exist, continue
        }
      })
    );
    
    // Archive coverage reports
    try {
      await fs.cp(
        "./coverage/integration",
        `${archiveDir}/coverage`,
        { recursive: true }
      ).catch(() => {});
    } catch {
      // Coverage might not exist
    }
    
    console.log(`📦 Test results archived to ${archiveDir}`);
  } catch (error) {
    console.error("Failed to archive test results:", error);
  }
}

/**
 * Clean up temporary resources and files
 */
async function cleanupTemporaryResources(): Promise<void> {
  try {
    const temporaryPaths = [
      "./tmp/integration",
      "./.data/test",
      "./logs/integration/test.log",
    ];
    
    await Promise.all(
      temporaryPaths.map(path => 
        fs.rm(path, { recursive: true, force: true }).catch(() => {})
      )
    );
    
    console.log("🧹 Temporary resources cleaned up");
  } catch (error) {
    console.error("Failed to cleanup temporary resources:", error);
  }
}

/**
 * Generate coverage summary report
 */
async function generateCoverageSummary(): Promise<void> {
  try {
    const coverageSummaryPath = "./coverage/integration/coverage-summary.json";
    const reportPath = "./test-results/integration/coverage-report.md";
    
    let coverageData: any = {};
    try {
      const coverageContent = await fs.readFile(coverageSummaryPath, "utf-8");
      coverageData = JSON.parse(coverageContent);
    } catch {
      console.log("⚠️ No coverage data found");
      return;
    }
    
    const coverageReport = `# Integration Test Coverage Report

## Overall Coverage
| Type | Percentage | Covered/Total |
|------|-----------|---------------|
| Statements | ${coverageData.total?.statements?.pct || 0}% | ${coverageData.total?.statements?.covered || 0}/${coverageData.total?.statements?.total || 0} |
| Branches | ${coverageData.total?.branches?.pct || 0}% | ${coverageData.total?.branches?.covered || 0}/${coverageData.total?.branches?.total || 0} |
| Functions | ${coverageData.total?.functions?.pct || 0}% | ${coverageData.total?.functions?.covered || 0}/${coverageData.total?.functions?.total || 0} |
| Lines | ${coverageData.total?.lines?.pct || 0}% | ${coverageData.total?.lines?.covered || 0}/${coverageData.total?.lines?.total || 0} |

## File Coverage Details
${Object.entries(coverageData)
  .filter(([key]) => key !== "total")
  .map(([file, data]: [string, any]) => {
    const fileName = path.basename(file);
    return `### ${fileName}
- **Statements:** ${data.statements?.pct || 0}%
- **Branches:** ${data.branches?.pct || 0}%  
- **Functions:** ${data.functions?.pct || 0}%
- **Lines:** ${data.lines?.pct || 0}%`;
  }).join("\n\n")}

---
*Coverage report generated on ${new Date().toISOString()}*`;

    await fs.writeFile(reportPath, coverageReport);
    console.log("📈 Coverage summary report generated");
  } catch (error) {
    console.error("Failed to generate coverage summary:", error);
  }
}

/**
 * Validate test environment state after completion
 */
async function validateTestEnvironment(): Promise<void> {
  try {
    const validationResults = {
      timestamp: new Date().toISOString(),
      environment: process.env.NODE_ENV,
      nodeVersion: process.version,
      memory: process.memoryUsage(),
      uptime: process.uptime(),
      validations: [] as string[],
    };
    
    // Check if all test directories are clean
    try {
      const tmpDirs = await fs.readdir("./tmp").catch(() => []);
      if (tmpDirs.length === 0) {
        validationResults.validations.push("✅ Temporary directories cleaned");
      } else {
        validationResults.validations.push(`⚠️ Temporary directories not empty: ${tmpDirs.join(", ")}`);
      }
    } catch {
      validationResults.validations.push("✅ No temporary directories found");
    }
    
    // Check memory usage
    const memoryUsageMB = process.memoryUsage().heapUsed / 1024 / 1024;
    if (memoryUsageMB < 500) {
      validationResults.validations.push(`✅ Memory usage normal: ${memoryUsageMB.toFixed(2)} MB`);
    } else {
      validationResults.validations.push(`⚠️ High memory usage: ${memoryUsageMB.toFixed(2)} MB`);
    }
    
    // Validate test result files exist
    const requiredFiles = ["summary.md", "coverage-report.md"];
    for (const file of requiredFiles) {
      try {
        await fs.access(`./test-results/integration/${file}`);
        validationResults.validations.push(`✅ ${file} generated successfully`);
      } catch {
        validationResults.validations.push(`❌ ${file} missing`);
      }
    }
    
    await fs.writeFile(
      "./test-results/integration/environment-validation.json",
      JSON.stringify(validationResults, null, 2)
    );
    
    console.log("🔍 Test environment validation completed");
    
    // Log validation summary
    const passed = validationResults.validations.filter(v => v.startsWith("✅")).length;
    const warnings = validationResults.validations.filter(v => v.startsWith("⚠️")).length;
    const failed = validationResults.validations.filter(v => v.startsWith("❌")).length;
    
    console.log(`Environment validation: ${passed} passed, ${warnings} warnings, ${failed} failed`);
    
  } catch (error) {
    console.error("Failed to validate test environment:", error);
  }
}