name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v5
        with:
          go-version-file: engine/go.mod
          cache-dependency-path: engine/go.sum
      - name: Build
        run: go build ./...

  test:
    name: test
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v5
        with:
          go-version-file: engine/go.mod
          cache-dependency-path: engine/go.sum
      - name: Test
        run: go test -v ./...

  lint:
    name: lint
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: engine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v5
        with:
          go-version-file: engine/go.mod
          cache-dependency-path: engine/go.sum
      - name: Lint
        run: |
          go vet ./...
