import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  GITHUB_ACCESS_TOKEN,
  GITHUB_USERNAME,
  GITHUB_REPOSITORY,
  DISCORD_CHANNEL_ID,
  JIRA_HOST,
  JIRA_EMAIL,
  JIRA_API_TOKEN,
  JIRA_PROJECT_KEY,
  JIRA_SPRINT_FIELD,
  JIRA_TRANSITION_CLOSE,
  // Optional custom Jira transition names (comma-separated supported)
  JIRA_TRANSITION_DONE,
  JIRA_TRANSITION_WONT_DO,
  JIRA_TRANSITION_REOPEN,
  DISCORD_DEV_GUILD_ID,
} = process.env;

if (
  !DISCORD_TOKEN ||
  !DISCORD_CLIENT_ID ||
  !GITHUB_ACCESS_TOKEN ||
  !GITHUB_USERNAME ||
  !GITHUB_REPOSITORY ||
  !DISCORD_CHANNEL_ID
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  GITHUB_ACCESS_TOKEN,
  GITHUB_USERNAME,
  GITHUB_REPOSITORY,
  DISCORD_CHANNEL_ID,
  JIRA_HOST,
  JIRA_EMAIL,
  JIRA_API_TOKEN,
  JIRA_PROJECT_KEY,
  JIRA_SPRINT_FIELD,
  JIRA_TRANSITION_CLOSE,
  JIRA_TRANSITION_DONE,
  JIRA_TRANSITION_WONT_DO,
  JIRA_TRANSITION_REOPEN,
  DISCORD_DEV_GUILD_ID,
};
