/*!
 * KVirtualStage Basic Automation Example
 * 
 * This example demonstrates the fundamental automation capabilities
 * of KVirtualStage, including session management, cursor movement,
 * clicking, typing, and recording.
 */

use anyhow::Result;
use kvirtualstage::*;
use std::time::Duration;
use tokio::time::sleep;

#[tokio::main]
async fn main() -> Result<()> {
    // Initialize logging
    tracing_subscriber::fmt()
        .with_env_filter("kvirtualstage=info")
        .init();

    println!("🚀 KVirtualStage Basic Automation Example");
    println!("=========================================");

    // Initialize the KVirtualStage API
    println!("📡 Initializing KVirtualStage API...");
    let api = KVirtualStageAPI::new().await?;
    println!("✅ API initialized successfully!");

    // Create a new automation session
    println!("\n📦 Creating new session...");
    let session_id = api.create_session(
        "demo_user".to_string(),
        "basic_automation_demo".to_string(),
        "ubuntu-xfce".to_string(),
    ).await?;
    println!("✅ Session created: {}", session_id);

    // Start recording the session
    println!("\n🎥 Starting session recording...");
    let recording_id = api.start_recording(
        &session_id,
        "basic_automation_demo.mp4",
        Some("high".to_string()),
    ).await?;
    println!("✅ Recording started: {}", recording_id);

    // Demonstrate cursor movement
    println!("\n🖱️  Demonstrating natural cursor movement...");
    let cursor_positions = vec![
        (100.0, 100.0, "Top-left area"),
        (500.0, 200.0, "Center-right"),
        (300.0, 400.0, "Lower-center"),
        (700.0, 100.0, "Top-right corner"),
        (200.0, 300.0, "Left-center"),
    ];

    for (i, (x, y, description)) in cursor_positions.iter().enumerate() {
        println!("  📍 Moving to {}: ({:.0}, {:.0})", description, x, y);
        api.move_cursor(&session_id, *x, *y).await?;
        
        // Small delay to make movements visible
        sleep(Duration::from_millis(800)).await;
        
        // Click at this position
        if i % 2 == 0 {
            println!("  🖱️  Left click at current position");
            api.click(&session_id, None).await?;
        } else {
            println!("  🖱️  Right click at current position");
            api.click(&session_id, Some("right".to_string())).await?;
        }
        
        sleep(Duration::from_millis(500)).await;
    }

    // Demonstrate typing
    println!("\n⌨️  Demonstrating natural typing...");
    let typing_examples = vec![
        "Hello, World!",
        "This is a demonstration of KVirtualStage automation.",
        "Natural typing with human-like timing and rhythm.",
        "Special characters: !@#$%^&*()_+-=[]{}|;':\",./<>?",
        "Numbers and mixed content: 123 ABC abc 456 XYZ xyz",
        "Testing different typing speeds and patterns...",
    ];

    for (i, text) in typing_examples.iter().enumerate() {
        println!("  📝 Typing example {}: \"{}\"", i + 1, text);
        api.type_text(&session_id, text).await?;
        
        // Add line breaks between examples
        if i < typing_examples.len() - 1 {
            api.type_text(&session_id, "\n").await?;
        }
        
        sleep(Duration::from_millis(1000)).await;
    }

    // Demonstrate a complete workflow
    println!("\n🔄 Executing a complete automation workflow...");
    
    use automation_engine::{AutomationWorkflow, WorkflowStep, StepAction, Point, MouseButton};
    
    let workflow = AutomationWorkflow {
        name: "Basic Demo Workflow".to_string(),
        description: "A demonstration workflow showing various automation capabilities".to_string(),
        continue_on_error: false,
        steps: vec![
            WorkflowStep {
                name: "Navigate to text area".to_string(),
                action: StepAction::MoveCursor { to: Point::new(400.0, 250.0) },
                timeout: Some(Duration::from_secs(5)),
            },
            WorkflowStep {
                name: "Click to focus".to_string(),
                action: StepAction::Click { 
                    position: Point::new(400.0, 250.0), 
                    button: MouseButton::Left 
                },
                timeout: Some(Duration::from_secs(5)),
            },
            WorkflowStep {
                name: "Clear existing content".to_string(),
                action: StepAction::KeySequence { 
                    keys: vec!["ctrl".to_string(), "a".to_string()] 
                },
                timeout: Some(Duration::from_secs(5)),
            },
            WorkflowStep {
                name: "Type workflow message".to_string(),
                action: StepAction::Type { 
                    text: "\n=== WORKFLOW AUTOMATION DEMO ===\n\nThis text was generated by an automated workflow!\n\nCapabilities demonstrated:\n- Natural cursor movement\n- Human-like clicking\n- Realistic typing simulation\n- Complex workflow execution\n- Session recording\n\nKVirtualStage makes desktop automation feel natural and human-like.".to_string() 
                },
                timeout: Some(Duration::from_secs(30)),
            },
            WorkflowStep {
                name: "Save document".to_string(),
                action: StepAction::KeySequence { 
                    keys: vec!["ctrl".to_string(), "s".to_string()] 
                },
                timeout: Some(Duration::from_secs(10)),
            },
            WorkflowStep {
                name: "Move to final position".to_string(),
                action: StepAction::MoveCursor { to: Point::new(600.0, 400.0) },
                timeout: Some(Duration::from_secs(5)),
            },
            WorkflowStep {
                name: "Final celebration click".to_string(),
                action: StepAction::Click { 
                    position: Point::new(600.0, 400.0), 
                    button: MouseButton::Left 
                },
                timeout: Some(Duration::from_secs(5)),
            },
        ],
    };

    println!("  🎯 Executing workflow: '{}'", workflow.name);
    let workflow_result = api.execute_workflow(&session_id, workflow).await?;
    
    println!("  📊 Workflow execution results:");
    println!("    - Total steps: {}", workflow_result.total_steps);
    println!("    - Successful steps: {}", workflow_result.successful_steps);
    println!("    - Execution time: {} ms", workflow_result.execution_time_ms);
    println!("    - Success: {}", workflow_result.success);
    
    if !workflow_result.success {
        println!("    - Errors: {:?}", workflow_result.errors);
    }

    // Stop recording
    println!("\n🛑 Stopping session recording...");
    let output_path = api.stop_recording(&session_id).await?;
    println!("✅ Recording saved to: {}", output_path);

    // Display session information
    println!("\n📋 Session Information:");
    let session_info = api.get_session_info(&session_id).await?;
    println!("  - Session ID: {}", session_info.session_id);
    println!("  - User ID: {}", session_info.user_id);
    println!("  - Desktop Type: {}", session_info.desktop_type);
    println!("  - Status: {}", session_info.status);
    println!("  - Recording Active: {}", session_info.recording_active);
    println!("  - Current Position: ({:.0}, {:.0})", 
             session_info.automation_context.current_position.x,
             session_info.automation_context.current_position.y);

    // List all active sessions
    println!("\n📝 All Active Sessions:");
    let all_sessions = api.list_sessions().await?;
    for (i, session) in all_sessions.iter().enumerate() {
        println!("  {}. {} (User: {}, Desktop: {})", 
                 i + 1, session.session_id, session.user_id, session.desktop_type);
    }

    // Store some example credentials
    println!("\n🔐 Demonstrating credential storage...");
    let mut additional_fields = std::collections::HashMap::new();
    additional_fields.insert("environment".to_string(), "demo".to_string());
    additional_fields.insert("notes".to_string(), "Created during basic automation demo".to_string());

    let credential_id = api.store_credential(
        &session_id,
        "demo_service",
        "demo_user",
        "secure_password_123",
        Some(additional_fields),
    ).await?;
    println!("✅ Credential stored with ID: {}", credential_id);

    // Cleanup
    println!("\n🧹 Cleaning up demo session...");
    let cleaned_sessions = api.cleanup_expired_sessions(0).await?;
    println!("✅ Cleaned up {} session(s): {:?}", cleaned_sessions.len(), cleaned_sessions);

    println!("\n🎉 Basic automation demo completed successfully!");
    println!("📹 Recording saved to: {}", output_path);
    println!("💡 This example demonstrated:");
    println!("   - Session creation and management");
    println!("   - Natural cursor movement with WindMouse 2.0");
    println!("   - Human-like clicking simulation");
    println!("   - Natural typing with realistic timing");
    println!("   - Complex workflow execution");
    println!("   - Session recording and playback");
    println!("   - Secure credential storage");
    println!("   - Proper cleanup and resource management");

    Ok(())
}

/// Additional helper function to demonstrate error handling
async fn demonstrate_error_handling() -> Result<()> {
    println!("\n🚨 Demonstrating error handling...");
    
    let api = KVirtualStageAPI::new().await?;
    let invalid_session_id = "non_existent_session";
    
    // This should fail gracefully
    match api.move_cursor(invalid_session_id, 100.0, 100.0).await {
        Ok(_) => println!("  ❌ Unexpected success"),
        Err(e) => println!("  ✅ Properly handled error: {}", e),
    }
    
    // This should also fail gracefully
    match api.get_session_info(invalid_session_id).await {
        Ok(_) => println!("  ❌ Unexpected success"),
        Err(e) => println!("  ✅ Properly handled error: {}", e),
    }
    
    println!("✅ Error handling demonstration completed");
    Ok(())
}

/// Function to demonstrate performance monitoring
async fn demonstrate_performance_monitoring(api: &KVirtualStageAPI, session_id: &str) -> Result<()> {
    println!("\n📊 Demonstrating performance monitoring...");
    
    use std::time::Instant;
    
    // Measure cursor movement performance
    let start_time = Instant::now();
    for i in 0..10 {
        let x = 100.0 + (i as f64 * 50.0);
        let y = 150.0 + (i as f64 * 20.0);
        api.move_cursor(session_id, x, y).await?;
    }
    let cursor_duration = start_time.elapsed();
    println!("  🖱️  10 cursor movements took: {:?}", cursor_duration);
    
    // Measure typing performance
    let start_time = Instant::now();
    api.type_text(session_id, "Performance monitoring test with various characters!").await?;
    let typing_duration = start_time.elapsed();
    println!("  ⌨️  Typing 53 characters took: {:?}", typing_duration);
    
    // Measure API response time
    let start_time = Instant::now();
    let _session_info = api.get_session_info(session_id).await?;
    let api_duration = start_time.elapsed();
    println!("  📡 API response time: {:?}", api_duration);
    
    println!("✅ Performance monitoring completed");
    Ok(())
}