#!/usr/bin/env python3
"""v36 3e-Evolve: fuzz schedule cross-repo evolution.

Reads all cargo-fuzz targets across the fleet, identifies gaps
(crates without fuzz), and produces a PR-ready patch script.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def list_rust_crates() -> list[Path]:
    """List all directories containing Cargo.toml under REPO_ROOT."""
    return sorted(p.parent for p in REPO_ROOT.rglob("Cargo.toml")
                  if "target" not in p.parts and "node_modules" not in p.parts)


def has_fuzz(crate: Path) -> bool:
    return (crate / "fuzz").is_dir() or (crate / "fuzz_targets").is_dir()


def main() -> int:
    ap = argparse.ArgumentParser(description="Evolve fuzz cross-repo")
    ap.add_argument("--json", action="store_true", help="JSON output")
    ap.add_argument("--pr-script", type=Path, help="Write PR-ready patch script")
    args = ap.parse_args()

    crates = list_rust_crates()
    without_fuzz = [c for c in crates if not has_fuzz(c)]
    report = {
        "total_crates": len(crates),
        "with_fuzz": len(crates) - len(without_fuzz),
        "without_fuzz": len(without_fuzz),
        "gaps": [str(c.relative_to(REPO_ROOT)) for c in without_fuzz[:20]],
    }

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Total crates: {report['total_crates']}")
        print(f"With fuzz:    {report['with_fuzz']}")
        print(f"Without fuzz: {report['without_fuzz']}")
        for g in report["gaps"]:
            print(f"  MISS: {g}")

    if args.pr_script:
        script = ["#!/usr/bin/env bash", "# Auto-generated by evolve-fuzz", "set -euo pipefail", ""]
        for c in without_fuzz[:10]:
            rel = c.relative_to(REPO_ROOT)
            script += [
                f"echo '=== {rel} =='",
                f"cd \"{REPO_ROOT / rel}\"",
                'cargo fuzz init 2>/dev/null || echo "  fuzz already exists"',
                "",
            ]
        args.pr_script.write_text("\n".join(script) + "\n")
        args.pr_script.chmod(0o755)
        print(f"PR script: {args.pr_script}")

    return 0 if report["without_fuzz"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
