#!/usr/bin/env bash
#==============================================================================
# tools/pillar-fleet/cliff-sync.sh — CHANGELOG Fleet Sync
#
# Scans all repos for cliff.toml, validates structure, flags drift.
# Designed for 100-concurrent-agent parallel execution.
#
# Usage:
#   cliff-sync.sh                          # Scan all repos
#   cliff-sync.sh --repos "r1 r2 r3"       # Specific repos
#   cliff-sync.sh --fix                    # Auto-fix missing cliff.toml (copy template)
#   cliff-sync.sh --help                   # This message
#==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FIX_MODE=false
REPO_LIST=""
DATE_STAMP=$(date -u +%Y-%m-%d)
HAS_CLIFF=0
MISSING_CLIFF=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repos) REPO_LIST="$2"; shift 2 ;;
        --fix)   FIX_MODE=true; shift ;;
        --help)  head -20 "$0"; exit 0 ;;
        *)       echo "Unknown: $1"; exit 1 ;;
    esac
done

# Find candidate repos (max depth 2 from REPO_ROOT)
if [[ -z "$REPO_LIST" ]]; then
    CANDIDATES=$(find "$REPO_ROOT" -maxdepth 2 -name ".git" -type d 2>/dev/null | sed 's|/\.git||' | sort -u || true)
else
    CANDIDATES=""
    for r in $REPO_LIST; do
        if [[ -d "$REPO_ROOT/$r/.git" ]]; then
            CANDIDATES="$CANDIDATES $REPO_ROOT/$r"
        fi
    done
fi

# Template cliff.toml if we need to create one
create_template() {
    local target="$1"
    cat > "$target" << 'CLIFF'
[changelog]
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% endfor %}
{% endfor %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"

[git]
conventional_commits = true
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^docs", group = "Documentation" },
    { message = "^refactor", group = "Refactor" },
    { message = "^test", group = "Tests" },
    { message = "^.*", group = "Other" },
]
CLIFF
}

{
    echo "# CHANGELOG Fleet Sync — ${DATE_STAMP}"
    echo ""
    echo "| Repo | cliff.toml | Status |"
    echo "|---|---|---|"

    for repo_dir in $CANDIDATES; do
        repo_name=$(basename "$repo_dir")
        cliff_file="$repo_dir/cliff.toml"

        if [[ -f "$cliff_file" ]]; then
            HAS_CLIFF=$(( HAS_CLIFF + 1 ))
            # Validate basic structure
            if grep -q "conventional_commits" "$cliff_file" 2>/dev/null; then
                echo "| $repo_name | ✅ | Valid |"
            else
                echo "| $repo_name | ⚠️ | Missing conventional_commits |"
            fi
        else
            MISSING_CLIFF=$(( MISSING_CLIFF + 1 ))
            echo "| $repo_name | ❌ | Missing |"

            if $FIX_MODE; then
                create_template "$cliff_file"
                echo "| $repo_name | ➕ | Created from template |"
            fi
        fi
    done

    echo ""
    echo "## Summary"
    echo ""
    echo "- **Repos with cliff.toml:** $HAS_CLIFF"
    echo "- **Repos missing cliff.toml:** $MISSING_CLIFF"
    echo "- **Generated by:** \`tools/pillar-fleet/cliff-sync.sh\`"
} > /tmp/cliff-fleet-sync-${DATE_STAMP}.md

if $FIX_MODE; then
    echo "Fix mode enabled. Created cliff.toml for $MISSING_CLIFF repos." >&2
else
    echo "Scan complete: $HAS_CLIFF with cliff.toml, $MISSING_CLIFF missing. Use --fix to create." >&2
fi

echo "Report: /tmp/cliff-fleet-sync-${DATE_STAMP}.md" >&2
