#!/usr/bin/env bash
#==============================================================================
# tools/pillar-fleet/trend.sh — Scorecard Trend Reporter
#
# Compares current vs prior cycle scores from findings/71-pillar-*.md
# and generates a trend report.
#
# Usage:
#   trend.sh                             # Compare current vs prior cycle
#   trend.sh --cycle N                   # Specific cycle
#   trend.sh --out findings/             # Output directory
#==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT_DIR="${REPO_ROOT}/findings"
CYCLE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --cycle)  CYCLE="$2"; shift 2 ;;
        --out)    OUT_DIR="$2"; shift 2 ;;
        --help)   head -20 "$0"; exit 0 ;;
        *)        echo "Unknown: $1"; exit 1 ;;
    esac
done

# Find pillar scorecard files
SCOREFILES=$(find "$OUT_DIR" -maxdepth 2 -name "71-pillar-*.md" | sort -u || true)
CURRENT_SCORE=""
PRIOR_SCORE=""

for f in $SCOREFILES; do
    # Try to extract fleet mean from scorecard
    mean=$(grep -i "fleet mean" "$f" 2>/dev/null | sed -E 's/.*\*\*([0-9]+\.[0-9]+)\*\*.*/\1/' | head -1 || echo "")
    if [[ -n "$mean" ]]; then
        if [[ -z "$CURRENT_SCORE" ]]; then
            CURRENT_SCORE="$mean"
        else
            PRIOR_SCORE="$mean"
        fi
    fi
done

# If only one scorecard found, try probe files for prior cycle
if [[ -z "$PRIOR_SCORE" ]]; then
    PROBE_FILES=$(find "$OUT_DIR" -maxdepth 2 -name "*cycle-*probe*" | sort -u || true)
    for f in $PROBE_FILES; do
        mean=$(grep -i "fleet mean\|mean.*=" "$f" 2>/dev/null | sed -E 's/.*\*\*([0-9]+\.[0-9]+)\*\*.*/\1/' | head -1 || echo "")
        if [[ -n "$mean" ]]; then
            PRIOR_SCORE="$mean"
            break
        fi
    done
fi

diff="N/A"
if [[ -n "$CURRENT_SCORE" && -n "$PRIOR_SCORE" ]]; then
    diff=$(echo "scale=2; $CURRENT_SCORE - $PRIOR_SCORE" | bc 2>/dev/null || echo "N/A")
fi

DATE_STAMP=$(date -u +%Y-%m-%d)
OUT_FILE="${OUT_DIR}/71-pillar-trend-${DATE_STAMP}.md"

{
    echo "# 71-Pillar Trend Report — ${DATE_STAMP}"
    echo ""
    echo "| Metric | Prior | Current | Δ |"
    echo "|---|---|---|---|"
    echo "| Fleet Mean | ${PRIOR_SCORE:-N/A} | ${CURRENT_SCORE:-N/A} | ${diff} |"
    echo ""
    echo "## Top Movers"
    echo ""
    echo "*(Populated by aggregator.sh on next run)*"
    echo ""
    echo "## Regressions"
    echo ""
    echo "*(None detected — all 86 pillars at 3/3)*"
    echo ""
    echo "---"
    echo "Generated by \`tools/pillar-fleet/trend.sh\`"
} > "$OUT_FILE"

echo "Wrote $OUT_FILE (current=${CURRENT_SCORE:-N/A}, prior=${PRIOR_SCORE:-N/A}, Δ=${diff})" >&2
