#!/usr/bin/env python3
"""mTLS fleet config generator v2 — generates per-substrate mTLS YAML.

Pillar L52.1 (cycle-22 P2-lift final). Generates mTLS configuration stubs
for each pheno-* substrate crate in the monorepo.

Usage:
    python3 tools/mtls-fleet/mtls_v2.py [--output-dir .mtls]
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
MTLS_TEMPLATE = """# mTLS configuration for {name}
# Auto-generated by tools/mtls-fleet/mtls_v2.py

mtls:
  enabled: true
  cert_path: certs/{name}.crt
  key_path: certs/{name}.key
  ca_path: certs/ca.crt
  verify_peer: true
  min_tls_version: "1.3"

# Override via env vars:
#   MTLS_ENABLED=false
#   MTLS_CERT_PATH=/custom/path
#   MTLS_KEY_PATH=/custom/path
"""


def find_substrate_dirs(root: Path) -> list[Path]:
    """Return all pheno-* directories that have a Cargo.toml."""
    substrates = []
    for p in root.iterdir():
        if p.is_dir() and p.name.startswith("pheno-") and (p / "Cargo.toml").exists():
            substrates.append(p)
    return sorted(substrates)


def write_mtls_config(substrate: Path, output_dir: Path) -> Path:
    name = substrate.name
    yaml_content = MTLS_TEMPLATE.format(name=name)
    out_path = output_dir / f"{name}.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(yaml_content)
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser(description="mTLS fleet config generator v2")
    ap.add_argument("--output-dir", default=".mtls", help="Output directory for YAML configs (default: .mtls)")
    args = ap.parse_args()
    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = REPO_ROOT / output_dir

    substrates = find_substrate_dirs(REPO_ROOT)
    if not substrates:
        print("No pheno-* substrate dirs found", file=sys.stderr)
        return 1

    generated = []
    for sub in substrates:
        path = write_mtls_config(sub, output_dir)
        generated.append(path)
        print(f"  + {path.relative_to(REPO_ROOT)}")

    print(f"\nGenerated {len(generated)} mTLS configs in {output_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
