#!/usr/bin/env python3
"""v36 3e-Evolve: perf-benchmark cross-repo evolution.

Discovers crates with criterion/bench targets, identifies gaps,
produces a PR-ready patch script.
"""
from __future__ import annotations

import argparse, json, sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def list_rust_crates():
    return sorted(p.parent for p in REPO_ROOT.rglob("Cargo.toml")
                  if "target" not in p.parts and "node_modules" not in p.parts)


def has_bench(crate: Path) -> bool:
    return (crate / "benches").is_dir()


def main() -> int:
    ap = argparse.ArgumentParser(description="Evolve perf cross-repo")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--pr-script", type=Path)
    args = ap.parse_args()
    crates = list_rust_crates()
    without = [c for c in crates if not has_bench(c)]
    report = {"total": len(crates), "with_bench": len(crates) - len(without), "without_bench": len(without),
              "gaps": [str(c.relative_to(REPO_ROOT)) for c in without[:20]]}
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"Total crates: {report['total']}\nWith bench: {report['with_bench']}\nWithout: {report['without_bench']}")
        for g in report["gaps"]:
            print(f"  MISS: {g}")
    if args.pr_script:
        lines = ["#!/usr/bin/env bash", "# Auto-generated by evolve-perf", "set -euo pipefail", ""]
        for c in without[:10]:
            rel = c.relative_to(REPO_ROOT)
            lines += [f"echo '=== {rel} =='", f"mkdir -p \"{rel}/benches\"",
                      f"cat > \"{rel}/benches/bench.rs\" << 'EOF'\nuse criterion::{criterion_group, criterion_main, Criterion};\npub fn bench(c: &mut Criterion) {{}}\ncriterion_group!(benches, bench);\ncriterion_main!(benches);\nEOF\n"]
        args.pr_script.write_text("\n".join(lines) + "\n")
        args.pr_script.chmod(0o755)
    return 0 if report["without_bench"] == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
