#!/usr/bin/env bash
#==============================================================================
# tools/adr-index-fleet/aggregator.sh — Fleet ADR Index Aggregator
#
# Scans all 86 repos for docs/adr/ directories and builds a unified
# ADR index. Designed for 100-concurrent-agent execution.
#
# Usage:
#   aggregator.sh                            # Scan root + subdirs, write INDEX.md
#   aggregator.sh --repos "repo1 repo2"      # Scan specific repos only
#   aggregator.sh --write-dir ./docs/adr/    # Output to custom path
#   aggregator.sh --help                     # This message
#
# Output: FLEET-ADR-INDEX.md in target directory listing all ADRs across all repos
#==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WRITE_DIR="${REPO_ROOT}"
REPO_LIST=""
DATE_STAMP=$(date -u +%Y-%m-%d)
TOTAL_ADRS=0
REPOS_WITH_ADRS=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repos)      REPO_LIST="$2"; shift 2 ;;
        --write-dir)  WRITE_DIR="$2"; shift 2 ;;
        --help)       head -20 "$0"; exit 0 ;;
        *)            echo "Unknown: $1"; exit 1 ;;
    esac
done

mkdir -p "$WRITE_DIR"
OUTPUT_FILE="${WRITE_DIR}/FLEET-ADR-INDEX.md"

# --- Find repos ---
if [[ -z "$REPO_LIST" ]]; then
    # Auto-discover repos: look for repos with docs/adr/ dirs
    CANDIDATES=$(find "$REPO_ROOT" -maxdepth 3 -path "*/docs/adr" -type d 2>/dev/null | sort -u || true)
else
    CANDIDATES=""
    for r in $REPO_LIST; do
        if [[ -d "$REPO_ROOT/$r/docs/adr" ]]; then
            CANDIDATES="$CANDIDATES $REPO_ROOT/$r/docs/adr"
        fi
    done
fi

# --- Build index ---
{
    echo "# Fleet ADR Index"
    echo ""
    echo "**Generated:** $DATE_STAMP | **Source:** Repo root scan"
    echo ""
    echo "| Repo | ADR Count | Latest ADR | Date Range |"
    echo "|---|---|---|---|"

    for adr_dir in $CANDIDATES; do
        repo_name=$(echo "$adr_dir" | sed -E "s|$REPO_ROOT/||" | sed -E 's|/docs/adr.*||')
        adr_count=$(find "$adr_dir" -maxdepth 1 -name "ADR-*.md" 2>/dev/null | wc -l | tr -d ' ')
        latest_adr=$(find "$adr_dir" -maxdepth 1 -name "ADR-*.md" 2>/dev/null | sort | tail -1 | xargs basename 2>/dev/null || echo "N/A")
        latest_date=$(find "$adr_dir" -maxdepth 1 -name "ADR-*.md" 2>/dev/null -exec stat -f "%Sm" {} \; 2>/dev/null | sort | tail -1 || echo "N/A")

        echo "| $repo_name | $adr_count | $latest_adr | $latest_date |"
        TOTAL_ADRS=$(( TOTAL_ADRS + adr_count ))
        REPOS_WITH_ADRS=$(( REPOS_WITH_ADRS + 1 ))
    done

    echo ""
    echo "## Summary"
    echo ""
    echo "- **Repos with ADRs:** $REPOS_WITH_ADRS"
    echo "- **Total ADRs:** $TOTAL_ADRS"
    echo "- **Generated by:** \`tools/adr-index-fleet/aggregator.sh\`"
} > "$OUTPUT_FILE"

echo "Wrote $OUTPUT_FILE ($REPOS_WITH_ADRS repos, $TOTAL_ADRS ADRs)" >&2
