// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CALENDAR_HOST_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CALENDAR_HOST_METHOD0
typedef void (*UniffiCallbackInterfaceCalendarHostMethod0)(uint64_t, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CALENDAR_HOST
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_CALENDAR_HOST
typedef struct UniffiVTableCallbackInterfaceCalendarHost {
    UniffiCallbackInterfaceCalendarHostMethod0 _Nonnull listEvents;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceCalendarHost;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_AUDITAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_AUDITAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_auditapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_AUDITAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_AUDITAPI
void uniffi_focus_ffi_fn_free_auditapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_AUDITAPI_HEAD_HASH
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_AUDITAPI_HEAD_HASH
RustBuffer uniffi_focus_ffi_fn_method_auditapi_head_hash(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_AUDITAPI_RECENT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_AUDITAPI_RECENT
RustBuffer uniffi_focus_ffi_fn_method_auditapi_recent(void*_Nonnull ptr, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_AUDITAPI_VERIFY_CHAIN
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_AUDITAPI_VERIFY_CHAIN
int8_t uniffi_focus_ffi_fn_method_auditapi_verify_chain(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_COACHINGCONFIG
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_COACHINGCONFIG
void*_Nonnull uniffi_focus_ffi_fn_clone_coachingconfig(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_COACHINGCONFIG
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_COACHINGCONFIG
void uniffi_focus_ffi_fn_free_coachingconfig(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CONSTRUCTOR_COACHINGCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CONSTRUCTOR_COACHINGCONFIG_NEW
void*_Nonnull uniffi_focus_ffi_fn_constructor_coachingconfig_new(RustBuffer endpoint, RustBuffer api_key, RustBuffer model, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_CONNECTORAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_CONNECTORAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_connectorapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_CONNECTORAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_CONNECTORAPI
void uniffi_focus_ffi_fn_free_connectorapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_CONNECTORAPI_CONNECT_CANVAS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_CONNECTORAPI_CONNECT_CANVAS
void uniffi_focus_ffi_fn_method_connectorapi_connect_canvas(void*_Nonnull ptr, RustBuffer instance_url, RustBuffer code, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_CONNECTORAPI_CONNECT_GCAL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_CONNECTORAPI_CONNECT_GCAL
void uniffi_focus_ffi_fn_method_connectorapi_connect_gcal(void*_Nonnull ptr, RustBuffer code, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_CONNECTORAPI_CONNECT_GITHUB
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_CONNECTORAPI_CONNECT_GITHUB
void uniffi_focus_ffi_fn_method_connectorapi_connect_github(void*_Nonnull ptr, RustBuffer pat, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_EVALAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_EVALAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_evalapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_EVALAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_EVALAPI
void uniffi_focus_ffi_fn_free_evalapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_EVALAPI_TICK
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_EVALAPI_TICK
RustBuffer uniffi_focus_ffi_fn_method_evalapi_tick(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_FOCALPOINTCORE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_FOCALPOINTCORE
void*_Nonnull uniffi_focus_ffi_fn_clone_focalpointcore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_FOCALPOINTCORE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_FOCALPOINTCORE
void uniffi_focus_ffi_fn_free_focalpointcore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CONSTRUCTOR_FOCALPOINTCORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CONSTRUCTOR_FOCALPOINTCORE_NEW
void*_Nonnull uniffi_focus_ffi_fn_constructor_focalpointcore_new(RustBuffer storage_path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_APP_VERSION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_APP_VERSION
RustBuffer uniffi_focus_ffi_fn_method_focalpointcore_app_version(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_AUDIT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_AUDIT
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_audit(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_CONNECTOR
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_CONNECTOR
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_connector(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_EVAL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_EVAL
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_eval(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_GENERATE_BUBBLE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_GENERATE_BUBBLE
RustBuffer uniffi_focus_ffi_fn_method_focalpointcore_generate_bubble(void*_Nonnull ptr, RustBuffer event, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_HOST_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_HOST_EVENTS
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_host_events(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_MASCOT_STATE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_MASCOT_STATE
RustBuffer uniffi_focus_ffi_fn_method_focalpointcore_mascot_state(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_MUTATIONS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_MUTATIONS
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_mutations(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_PENALTY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_PENALTY
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_penalty(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_POLICY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_POLICY
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_policy(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_PROPOSE_RULE_FROM_NL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_PROPOSE_RULE_FROM_NL
RustBuffer uniffi_focus_ffi_fn_method_focalpointcore_propose_rule_from_nl(void*_Nonnull ptr, RustBuffer nl_spec, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_PUSH_MASCOT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_PUSH_MASCOT_EVENT
RustBuffer uniffi_focus_ffi_fn_method_focalpointcore_push_mascot_event(void*_Nonnull ptr, RustBuffer event, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_RITUALS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_RITUALS
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_rituals(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_RULES
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_RULES
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_rules(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_RULES_DSL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_RULES_DSL
RustBuffer uniffi_focus_ffi_fn_method_focalpointcore_rules_dsl(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_SET_CALENDAR_HOST
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_SET_CALENDAR_HOST
void uniffi_focus_ffi_fn_method_focalpointcore_set_calendar_host(void*_Nonnull ptr, uint64_t host, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_SET_COACHING
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_SET_COACHING
void uniffi_focus_ffi_fn_method_focalpointcore_set_coaching(void*_Nonnull ptr, RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_SYNC
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_SYNC
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_sync(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_TASKS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_TASKS
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_tasks(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_TEMPLATES
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_TEMPLATES
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_templates(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_WALLET
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_FOCALPOINTCORE_WALLET
void*_Nonnull uniffi_focus_ffi_fn_method_focalpointcore_wallet(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_HOSTEVENTAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_HOSTEVENTAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_hosteventapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_HOSTEVENTAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_HOSTEVENTAPI
void uniffi_focus_ffi_fn_free_hosteventapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_HOSTEVENTAPI_EMIT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_HOSTEVENTAPI_EMIT
void uniffi_focus_ffi_fn_method_hosteventapi_emit(void*_Nonnull ptr, RustBuffer dto, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_PENALTYAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_PENALTYAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_penaltyapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_PENALTYAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_PENALTYAPI
void uniffi_focus_ffi_fn_free_penaltyapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_PENALTYAPI_APPLY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_PENALTYAPI_APPLY
void uniffi_focus_ffi_fn_method_penaltyapi_apply(void*_Nonnull ptr, RustBuffer m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_PENALTYAPI_LOAD
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_PENALTYAPI_LOAD
RustBuffer uniffi_focus_ffi_fn_method_penaltyapi_load(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_PENALTYAPI_QUOTE_BYPASS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_PENALTYAPI_QUOTE_BYPASS
RustBuffer uniffi_focus_ffi_fn_method_penaltyapi_quote_bypass(void*_Nonnull ptr, int64_t cost, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_POLICYAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_POLICYAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_policyapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_POLICYAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_POLICYAPI
void uniffi_focus_ffi_fn_free_policyapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_POLICYAPI_BUILD_FROM_RECENT_DECISIONS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_POLICYAPI_BUILD_FROM_RECENT_DECISIONS
RustBuffer uniffi_focus_ffi_fn_method_policyapi_build_from_recent_decisions(void*_Nonnull ptr, int32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_RITUALSAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_RITUALSAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_ritualsapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_RITUALSAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_RITUALSAPI
void uniffi_focus_ffi_fn_free_ritualsapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RITUALSAPI_CAPTURE_INTENTION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RITUALSAPI_CAPTURE_INTENTION
void uniffi_focus_ffi_fn_method_ritualsapi_capture_intention(void*_Nonnull ptr, RustBuffer date, RustBuffer intention, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RITUALSAPI_GENERATE_EVENING_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RITUALSAPI_GENERATE_EVENING_SHUTDOWN
RustBuffer uniffi_focus_ffi_fn_method_ritualsapi_generate_evening_shutdown(void*_Nonnull ptr, RustBuffer actuals, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RITUALSAPI_GENERATE_MORNING_BRIEF
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RITUALSAPI_GENERATE_MORNING_BRIEF
RustBuffer uniffi_focus_ffi_fn_method_ritualsapi_generate_morning_brief(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_RULEMUTATION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_RULEMUTATION
void*_Nonnull uniffi_focus_ffi_fn_clone_rulemutation(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_RULEMUTATION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_RULEMUTATION
void uniffi_focus_ffi_fn_free_rulemutation(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RULEMUTATION_SET_ENABLED
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RULEMUTATION_SET_ENABLED
void uniffi_focus_ffi_fn_method_rulemutation_set_enabled(void*_Nonnull ptr, RustBuffer rule_id, int8_t enabled, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RULEMUTATION_UPSERT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RULEMUTATION_UPSERT
void uniffi_focus_ffi_fn_method_rulemutation_upsert(void*_Nonnull ptr, RustBuffer rule, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_RULEQUERY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_RULEQUERY
void*_Nonnull uniffi_focus_ffi_fn_clone_rulequery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_RULEQUERY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_RULEQUERY
void uniffi_focus_ffi_fn_free_rulequery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RULEQUERY_LIST_ENABLED
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_RULEQUERY_LIST_ENABLED
RustBuffer uniffi_focus_ffi_fn_method_rulequery_list_enabled(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_SYNCAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_SYNCAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_syncapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_SYNCAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_SYNCAPI
void uniffi_focus_ffi_fn_free_syncapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_SYNCAPI_CONNECTORS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_SYNCAPI_CONNECTORS
RustBuffer uniffi_focus_ffi_fn_method_syncapi_connectors(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_SYNCAPI_TICK
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_SYNCAPI_TICK
RustBuffer uniffi_focus_ffi_fn_method_syncapi_tick(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_TASKAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_TASKAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_taskapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_TASKAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_TASKAPI
void uniffi_focus_ffi_fn_free_taskapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_ADD
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_ADD
RustBuffer uniffi_focus_ffi_fn_method_taskapi_add(void*_Nonnull ptr, RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_LIST
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_LIST
RustBuffer uniffi_focus_ffi_fn_method_taskapi_list(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_MARK_DONE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_MARK_DONE
void uniffi_focus_ffi_fn_method_taskapi_mark_done(void*_Nonnull ptr, RustBuffer task_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TASKAPI_REMOVE
void uniffi_focus_ffi_fn_method_taskapi_remove(void*_Nonnull ptr, RustBuffer task_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_TEMPLATEAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_TEMPLATEAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_templateapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_TEMPLATEAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_TEMPLATEAPI
void uniffi_focus_ffi_fn_free_templateapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TEMPLATEAPI_INSTALL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TEMPLATEAPI_INSTALL
uint32_t uniffi_focus_ffi_fn_method_templateapi_install(void*_Nonnull ptr, RustBuffer pack_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TEMPLATEAPI_LIST_BUNDLED
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_TEMPLATEAPI_LIST_BUNDLED
RustBuffer uniffi_focus_ffi_fn_method_templateapi_list_bundled(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_WALLETAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_CLONE_WALLETAPI
void*_Nonnull uniffi_focus_ffi_fn_clone_walletapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_WALLETAPI
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_FREE_WALLETAPI
void uniffi_focus_ffi_fn_free_walletapi(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_WALLETAPI_APPLY_MUTATION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_WALLETAPI_APPLY_MUTATION
void uniffi_focus_ffi_fn_method_walletapi_apply_mutation(void*_Nonnull ptr, RustBuffer m, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_WALLETAPI_LOAD
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_METHOD_WALLETAPI_LOAD
RustBuffer uniffi_focus_ffi_fn_method_walletapi_load(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_INIT_CALLBACK_VTABLE_CALENDARHOST
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_FN_INIT_CALLBACK_VTABLE_CALENDARHOST
void uniffi_focus_ffi_fn_init_callback_vtable_calendarhost(UniffiVTableCallbackInterfaceCalendarHost* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_focus_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_focus_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_FREE
void ffi_focus_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_focus_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U8
void ffi_focus_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U8
void ffi_focus_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U8
void ffi_focus_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_focus_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I8
void ffi_focus_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I8
void ffi_focus_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I8
void ffi_focus_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_focus_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U16
void ffi_focus_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U16
void ffi_focus_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U16
void ffi_focus_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_focus_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I16
void ffi_focus_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I16
void ffi_focus_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I16
void ffi_focus_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_focus_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U32
void ffi_focus_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U32
void ffi_focus_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U32
void ffi_focus_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_focus_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I32
void ffi_focus_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I32
void ffi_focus_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I32
void ffi_focus_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_focus_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_U64
void ffi_focus_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_U64
void ffi_focus_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_U64
void ffi_focus_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_focus_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_I64
void ffi_focus_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_I64
void ffi_focus_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_I64
void ffi_focus_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_focus_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_F32
void ffi_focus_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_F32
void ffi_focus_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_F32
void ffi_focus_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_focus_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_F64
void ffi_focus_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_F64
void ffi_focus_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_F64
void ffi_focus_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_focus_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_POINTER
void ffi_focus_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_focus_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_POINTER
void ffi_focus_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_focus_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_focus_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_focus_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_focus_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_focus_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_POLL_VOID
void ffi_focus_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_focus_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_FREE_VOID
void ffi_focus_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_focus_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_AUDITAPI_HEAD_HASH
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_AUDITAPI_HEAD_HASH
uint16_t uniffi_focus_ffi_checksum_method_auditapi_head_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_AUDITAPI_RECENT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_AUDITAPI_RECENT
uint16_t uniffi_focus_ffi_checksum_method_auditapi_recent(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_AUDITAPI_VERIFY_CHAIN
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_AUDITAPI_VERIFY_CHAIN
uint16_t uniffi_focus_ffi_checksum_method_auditapi_verify_chain(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CONNECTORAPI_CONNECT_CANVAS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CONNECTORAPI_CONNECT_CANVAS
uint16_t uniffi_focus_ffi_checksum_method_connectorapi_connect_canvas(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CONNECTORAPI_CONNECT_GCAL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CONNECTORAPI_CONNECT_GCAL
uint16_t uniffi_focus_ffi_checksum_method_connectorapi_connect_gcal(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CONNECTORAPI_CONNECT_GITHUB
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CONNECTORAPI_CONNECT_GITHUB
uint16_t uniffi_focus_ffi_checksum_method_connectorapi_connect_github(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_EVALAPI_TICK
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_EVALAPI_TICK
uint16_t uniffi_focus_ffi_checksum_method_evalapi_tick(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_APP_VERSION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_APP_VERSION
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_app_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_AUDIT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_AUDIT
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_audit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_CONNECTOR
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_CONNECTOR
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_connector(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_EVAL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_EVAL
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_eval(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_GENERATE_BUBBLE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_GENERATE_BUBBLE
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_generate_bubble(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_HOST_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_HOST_EVENTS
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_host_events(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_MASCOT_STATE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_MASCOT_STATE
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_mascot_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_MUTATIONS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_MUTATIONS
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_mutations(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_PENALTY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_PENALTY
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_penalty(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_POLICY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_POLICY
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_policy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_PROPOSE_RULE_FROM_NL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_PROPOSE_RULE_FROM_NL
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_propose_rule_from_nl(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_PUSH_MASCOT_EVENT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_PUSH_MASCOT_EVENT
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_push_mascot_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_RITUALS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_RITUALS
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_rituals(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_RULES
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_RULES
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_rules(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_RULES_DSL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_RULES_DSL
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_rules_dsl(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_SET_CALENDAR_HOST
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_SET_CALENDAR_HOST
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_set_calendar_host(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_SET_COACHING
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_SET_COACHING
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_set_coaching(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_SYNC
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_SYNC
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_TASKS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_TASKS
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_tasks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_TEMPLATES
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_TEMPLATES
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_templates(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_WALLET
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_FOCALPOINTCORE_WALLET
uint16_t uniffi_focus_ffi_checksum_method_focalpointcore_wallet(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_HOSTEVENTAPI_EMIT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_HOSTEVENTAPI_EMIT
uint16_t uniffi_focus_ffi_checksum_method_hosteventapi_emit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_PENALTYAPI_APPLY
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_PENALTYAPI_APPLY
uint16_t uniffi_focus_ffi_checksum_method_penaltyapi_apply(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_PENALTYAPI_LOAD
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_PENALTYAPI_LOAD
uint16_t uniffi_focus_ffi_checksum_method_penaltyapi_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_PENALTYAPI_QUOTE_BYPASS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_PENALTYAPI_QUOTE_BYPASS
uint16_t uniffi_focus_ffi_checksum_method_penaltyapi_quote_bypass(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_POLICYAPI_BUILD_FROM_RECENT_DECISIONS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_POLICYAPI_BUILD_FROM_RECENT_DECISIONS
uint16_t uniffi_focus_ffi_checksum_method_policyapi_build_from_recent_decisions(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RITUALSAPI_CAPTURE_INTENTION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RITUALSAPI_CAPTURE_INTENTION
uint16_t uniffi_focus_ffi_checksum_method_ritualsapi_capture_intention(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RITUALSAPI_GENERATE_EVENING_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RITUALSAPI_GENERATE_EVENING_SHUTDOWN
uint16_t uniffi_focus_ffi_checksum_method_ritualsapi_generate_evening_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RITUALSAPI_GENERATE_MORNING_BRIEF
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RITUALSAPI_GENERATE_MORNING_BRIEF
uint16_t uniffi_focus_ffi_checksum_method_ritualsapi_generate_morning_brief(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RULEMUTATION_SET_ENABLED
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RULEMUTATION_SET_ENABLED
uint16_t uniffi_focus_ffi_checksum_method_rulemutation_set_enabled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RULEMUTATION_UPSERT
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RULEMUTATION_UPSERT
uint16_t uniffi_focus_ffi_checksum_method_rulemutation_upsert(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RULEQUERY_LIST_ENABLED
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_RULEQUERY_LIST_ENABLED
uint16_t uniffi_focus_ffi_checksum_method_rulequery_list_enabled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_SYNCAPI_CONNECTORS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_SYNCAPI_CONNECTORS
uint16_t uniffi_focus_ffi_checksum_method_syncapi_connectors(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_SYNCAPI_TICK
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_SYNCAPI_TICK
uint16_t uniffi_focus_ffi_checksum_method_syncapi_tick(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_ADD
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_ADD
uint16_t uniffi_focus_ffi_checksum_method_taskapi_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_LIST
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_LIST
uint16_t uniffi_focus_ffi_checksum_method_taskapi_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_MARK_DONE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_MARK_DONE
uint16_t uniffi_focus_ffi_checksum_method_taskapi_mark_done(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TASKAPI_REMOVE
uint16_t uniffi_focus_ffi_checksum_method_taskapi_remove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TEMPLATEAPI_INSTALL
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TEMPLATEAPI_INSTALL
uint16_t uniffi_focus_ffi_checksum_method_templateapi_install(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TEMPLATEAPI_LIST_BUNDLED
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_TEMPLATEAPI_LIST_BUNDLED
uint16_t uniffi_focus_ffi_checksum_method_templateapi_list_bundled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_WALLETAPI_APPLY_MUTATION
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_WALLETAPI_APPLY_MUTATION
uint16_t uniffi_focus_ffi_checksum_method_walletapi_apply_mutation(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_WALLETAPI_LOAD
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_WALLETAPI_LOAD
uint16_t uniffi_focus_ffi_checksum_method_walletapi_load(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_CONSTRUCTOR_COACHINGCONFIG_NEW
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_CONSTRUCTOR_COACHINGCONFIG_NEW
uint16_t uniffi_focus_ffi_checksum_constructor_coachingconfig_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_CONSTRUCTOR_FOCALPOINTCORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_CONSTRUCTOR_FOCALPOINTCORE_NEW
uint16_t uniffi_focus_ffi_checksum_constructor_focalpointcore_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CALENDARHOST_LIST_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_FOCUS_FFI_CHECKSUM_METHOD_CALENDARHOST_LIST_EVENTS
uint16_t uniffi_focus_ffi_checksum_method_calendarhost_list_events(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_FOCUS_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_FOCUS_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_focus_ffi_uniffi_contract_version(void
    
);
#endif

