name: cargo-audit
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches: [main]
    paths: ['Cargo.lock', 'Cargo.toml']
  pull_request:
    paths: ['Cargo.lock', 'Cargo.toml']
  schedule:
    - cron: '37 5 * * 3'
  workflow_dispatch:
jobs:
  audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.1
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
