name: cargo-deny
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: EmbarkStudios/cargo-deny-action@91bf2b620e09e18d6eb78b92e7861937469acedb
        with:
          rust-version: stable
          command: check
